spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
      username: sa
      password:

  jpa:
    database: h2
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
kakao:
  api:
    base-url: http://dapi.kakao.com
    key: KakaoAK c057223d4ddf5ee6ab702c0f70c1703b
    timeout:
      call-timeout: 3000
      connection-timeout: 500
      read-timeout: 1000
      write-timeout: 1000
---
spring:
  profiles: test

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.web: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN

